# AcademicHistoryProcess — puerto acordado grupo (CONTRIBUTING.md)
http.port=8093
cors.allow.origin=*

db.host=localhost
db.port=3306
db.name=elearning_academic_history
db.user=mule
db.password=mule123
